
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace PredikcijaKvaraStroja_KonzolnaAplikacija
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            PredikcijaKvaraStroja.ModelInput sampleData = new PredikcijaKvaraStroja.ModelInput()
            {
                Product_ID = @"L48179",
                Type = @"L",
                Air_temperature = 2963F,
                Process_temperature = 3071F,
                Rotational_speed = 1560F,
                Torque = 332F,
                Tool_wear = 186F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = PredikcijaKvaraStroja.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Machine_failure with predicted Machine_failure from sample data...\n\n");
            

            Console.WriteLine($"Product_ID: {@"L48179"}");
            Console.WriteLine($"Type: {@"M"}");
            Console.WriteLine($"Air_temperature: {2963F}");
            Console.WriteLine($"Process_temperature: {3071F}");
            Console.WriteLine($"Rotational_speed: {1560F}");
            Console.WriteLine($"Torque: {332F}");
            Console.WriteLine($"Tool_wear: {186F}");


            Console.WriteLine($"\n\nPredicted Machine_failure: {predictionResult.Prediction}\n\n Score: {predictionResult.Score}");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
