// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace ModelBuilder_Primjer_regresije
{
    public partial class PredikcijaCijeneNekretnine
    {
        /// <summary>
        /// model input class for PredikcijaCijeneNekretnine.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"address")]
            public string Address { get; set; }

            [ColumnName(@"bathrooms")]
            public float Bathrooms { get; set; }

            [ColumnName(@"bedrooms")]
            public float Bedrooms { get; set; }

            [ColumnName(@"finishedsqft")]
            public float Finishedsqft { get; set; }

            [ColumnName(@"lastsolddate")]
            public string Lastsolddate { get; set; }

            [ColumnName(@"lastsoldprice")]
            public float Lastsoldprice { get; set; }

            [ColumnName(@"latitude")]
            public float Latitude { get; set; }

            [ColumnName(@"longitude")]
            public float Longitude { get; set; }

            [ColumnName(@"neighborhood")]
            public string Neighborhood { get; set; }

            [ColumnName(@"totalrooms")]
            public float Totalrooms { get; set; }

            [ColumnName(@"usecode")]
            public string Usecode { get; set; }

            [ColumnName(@"yearbuilt")]
            public float Yearbuilt { get; set; }

            [ColumnName(@"zipcode")]
            public float Zipcode { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for PredikcijaCijeneNekretnine.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("PredikcijaCijeneNekretnine.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
