// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;

namespace DiplomskiRad_ModelBuilder_Primjer
{
    public partial class TitanicModel
    {
        /// <summary>
        /// model input class for TitanicModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"PassengerId")]
            public float PassengerId { get; set; }

            [ColumnName(@"Survived")]
            public float Survived { get; set; }

            [ColumnName(@"Pclass")]
            public float Pclass { get; set; }

            [ColumnName(@"Name")]
            public string Name { get; set; }

            [ColumnName(@"Sex")]
            public string Sex { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"SibSp")]
            public float SibSp { get; set; }

            [ColumnName(@"Parch")]
            public float Parch { get; set; }

            [ColumnName(@"Ticket")]
            public string Ticket { get; set; }

            [ColumnName(@"Fare")]
            public float Fare { get; set; }

            [ColumnName(@"Cabin")]
            public string Cabin { get; set; }

            [ColumnName(@"Embarked")]
            public string Embarked { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for TitanicModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName("PredictedLabel")]
            public float Prediction { get; set; }

            public float[] Score { get; set; }
        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("TitanicModel.zip");

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            MLContext mlContext = new MLContext();

            // Load model & create prediction engine
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);

            ModelOutput result = predEngine.Predict(input);
            return result;
        }
    }
}
