
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace PredikcijaCijeneNekretnine_KonzolnaAplikacija
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            PredikcijaCijeneNekretnine.ModelInput sampleData = new PredikcijaCijeneNekretnine.ModelInput()
            {
                Bathrooms = 2F,
                Bedrooms = 2F,
                Finishedsqft = 1463F,
                Totalrooms = 7F,
                Usecode = @"Condominium",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = PredikcijaCijeneNekretnine.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Lastsoldprice with predicted Lastsoldprice from sample data...\n\n");


            Console.WriteLine($"Bathrooms: {2F}");
            Console.WriteLine($"Bedrooms: {2F}");
            Console.WriteLine($"Finishedsqft: {1463F}");
            Console.WriteLine($"Lastsoldprice: {1950000F}");
            Console.WriteLine($"Totalrooms: {7F}");
            Console.WriteLine($"Usecode: {@"Condominium"}");


            Console.WriteLine($"\n\nPredicted Lastsoldprice: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}